- hosts: all
  sudo: yes
  tasks:
      - name: Install wget package (Debian based)
        action: apt pkg='wget' state=installed

      - name: Ensure dependencies are installed.
        apt: pkg=curl state=installed

      - name: install python-pycurl
        apt: pkg=python-pycurl state=latest

      - name: Add Jenkins apt repository key.
        apt_key:
          url: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
          state: present
          validate_certs: no

      - name: Add Jenkins apt repository.
        apt_repository:
          repo: "deb http://pkg.jenkins-ci.org/debian binary/"
          state: present
          update_cache: yes

      - name: Ensure Jenkins is installed.
        apt: pkg=jenkins state=installed

      - name: Download Jenkins Swarm Client
        get_url: dest=/tmp/swarm-client.jar url=http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/plugins/swarm-client/1.22/swarm-client-1.22-jar-with-dependencies.jar

      - name: Execute Swarm Client to start slave
        shell: "java -jar /tmp/swarm-client.jar -master http://192.168.50.4:8080 -username vagrant -password vagrant"





